# SVARA build contract (shared by all builders)

Stack: Node ≥22 ESM, ZERO npm dependencies. `node:http`, `node:sqlite` via `server/lib/db.js`, `node:crypto`. Frontend: vanilla ES modules, no build step. Schema: `server/db/001_init.sql` (read it). Existing libs: `server/lib/{config,db,auth}.js` (read them; do not rewrite). Never hardcode secrets.
Product rules: SVARA is NOT an AI doctor. Observational language only ("you've reported…"). No diagnosis, no prescriptions, no dosing, no medical claims, no single "health score" (only per-dimension "My Rhythm"). Demo products always say **"DEMO — NOT FOR SALE"**. No cannabis imagery/leaf/neon. Tone: calm, warm, premium.

## Ownership (do not edit files you don't own)
- **A Engine**: `server/engine/**`, `server/db/seed-data/**`, `server/db/seed.js`, `scripts/migrate.js`, `scripts/seed.js`
- **B Server**: `server/index.js`, `server/lib/{http,ratelimit,validate}.js`, `server/routes/**`, `server/integrations/**`, `scripts/build.js`, `test/**`, `Dockerfile`
- **C Frontend core+public**: `public/index.html`, `public/styles.css`, `public/js/{core,main,pages-public}.js`, `public/assets/**`
- **D Frontend app**: `public/app.css`, `public/js/{pages-app,pages-pro}.js`
- Lead (me): README, docs/*, .env.example

## Domain constants
Dimension keys (order): `sleep, energy, mood, relaxation, motivation, focus, recovery, social_connection, stress, overall_wellbeing`. First 8 are `primary` (in_snapshot=1, shown in My Rhythm); `stress` and `overall_wellbeing` are secondary. Labels: Sleep, Energy, Mood, Relaxation, Motivation, Focus, Recovery, Social connection, Stress ease, Overall wellbeing. ALL scores are 0–100 normalised so **higher = feels better** (stress is reverse-coded: label "Stress ease"). Raw answers 1–5 → `score=(raw-1)*25`, inverted when `questions.reverse=1`.
Goal keys: `night_routine 🌙 Better night routine`, `relaxation 🧘 More relaxation`, `energy ⚡ More energy`, `focus 🎯 Better focus`, `recovery 🏃 Recovery`, `mood 🙂 Better everyday mood`, `motivation 🔥 Motivation`, `social 🤝 Social wellbeing`.
Daily-context keys: `workload` (light|moderate|heavy), `exercised` (bool), `late_screens` (bool).
Baseline = first 7 distinct check-in days (kind `baseline`), then `daily`.
Consent types: terms, privacy, ai_processing, clinician_sharing, marketing, analytics. Latest row per type wins.
Demo accounts (is_demo=1, password `SvaraDemo!2025`): `maya@svara.demo` (Persona A: high energy, low relaxation, heavy workload), `arjun@svara.demo` (B: good sleep, variable motivation), `neha@svara.demo` (C: variable sleep, high work stress), `rohan@svara.demo` (D: balanced). `clinician@svara.demo` (CLINICIAN, "Dr. Demo Clinician", marked demo), `admin@svara.demo` (ADMIN). ~90 days of deterministic (seeded PRNG) synthetic history for personas, ending today. Maya has a `closed` clinician_report whose `decision`/`next_step` note makes her product-eligible; Arjun has a `requested` report awaiting the clinician.

## Engine module API (A implements, B calls). All sync, throw `Error` with `.status` on failure.
- `engine/scoring.js`: `DIMENSIONS`[{key,label,description,in_snapshot,sort_order}], `toScore(raw,reverse)`, `scoreAssessment(answers[{question_id,value}]) → {scores:{dim:0-100}, answered}` (validates ids against assessment pool; no composite score).
- `engine/trends.js`: `recordCheckIn(userId,{question_id,raw_value,note,kind,day})→row` (also upserts `wellness_scores`); `getRhythm(userId)→[{key,label,description,primary,has_data,current,baseline,delta7,direction('up'|'down'|'steady'),variability,consistency,series7:[{day,score}],series30:[{day,score}]}]`; `getTrends(userId,windowDays)→{window_days,dimensions:[{key,label,current,baseline,change,variability,consistency,direction,series:[{day,score}]}]}` (windows 7,14,30,90,365; caches `trend_snapshots`); `detectPatterns(userId)→[{id,dimension,kind,n,text}]` (workload/exercise/late-screen vs dimension comparisons, n≥3 each side, ≥8pt gap, observational wording); `baselineStatus(userId)→{days_completed,target:7,complete}`; `recordContext(userId,day,ctx)`.
- `engine/questions.js`: `selectQuestions(userId,{count})→{questions:[{id,dimension,question,response_type,options[5],reverse}],reasons:[string]}` using goals, recent trends, missing dimensions, `allowed_frequency_days`, sensitivity vs `preferences.max_sensitivity`, active flag, admin setting `ai.question_selection_enabled` (fallback rotation); `answeredTodayCount(userId)`. Only approved library questions; never invents any.
- `engine/reports.js`: `generateWeeklyReport(userId,{force})→{id,week_start,content}`; content = `{title:'YOUR WEEK IN SVARA',week_start,week_end,arrows:[{dimension,label,direction,delta}],reported:[string],reflection:string,next_week:string,disclaimer:'This summary reflects your reported information and is not medical advice or a diagnosis.',data_days}`; `buildClinicianReport(userId,rangeDays|null,{questions,comments})→content` = `{title:'SVARA CLINICIAN REPORT',generated_at,range_days,goals:[],lifestyle_context:{},dimensions:[{key,label,current,baseline,change,direction,variability,consistency}],recent_changes:[string],patterns:[string],user_comments,questions_to_discuss:[string],disclaimer}` (no diagnosis/prescription language).
- `engine/guide.js`: `respond(userId,{conversationId,message})→{conversationId,reply,safety_category,resources:[{type:'content'|'routine',title,link}],suggestions:[string],blocked:boolean,disabled:boolean}`. Pipeline: input safety classify → (non-NORMAL → templated safe reply, log safety_event) → intent routing (summary, explain metric, reflection, routine, weekly, clinician-prep, product question → education + clinician pathway, never a product push) → retrieve minimal context via `memory.js` → deterministic generator or optional LLM (`llm.js`, only if `LLM_PROVIDER=anthropic` + key + setting `ai.llm_enabled` + user `ai_processing` consent) with JSON-schema-validated output → claim guard → output safety check → persist to ai_conversations/ai_messages (rolling summary). If user has not granted `ai_processing` consent or setting `ai.guide_enabled` false → `{disabled:true, reply:'…turn on in My Privacy'}`.
- `engine/discovery.js`: `GOALS`[{key,label,emoji,dimensions[]}], `findRhythm(userId,goalKey)→{goal,snapshot:[{key,label,current,baseline,direction}],observations:[string],resources:[{title,slug,category,summary}],routine:{…routine row…},tracking_goal:{dimension,label,text},clinician_cta:{text},products:[]}` — `products` is ONLY populated if `productEligibility(userId).eligible`; `productEligibility(userId)→{eligible,reason}` (requires a consented clinician report with a `completed|closed` status AND a `next_step` note whose body contains the tag `[product-pathway]`, and product displayable gate).
- `engine/safety.js`: `classify(text)→{category,rule_label}` (categories NORMAL_WELLNESS, MEDICAL_QUESTION, MEDICATION_QUESTION, PRODUCT_DOSAGE, ADVERSE_REACTION, POTENTIAL_CRISIS, EMERGENCY; rules from `safety_rules` table, highest severity wins; negation/false-positive safe); `respondTo(category)→{reply}|null`; `logEvent({userId,category,rule_label,source,text,action})` (stores truncated, minimised excerpt).
- `engine/claims.js`: `checkText(text,{product}={})→{ok,violations:[{rule_id,label,severity,excerpt,reason}]}` (configurable `claim_rules` + product `restricted_claims`; simple negation handling so "does not treat" isn't flagged; product copy must also not exceed `approved_claims`-style content); `checkProduct(row)`, `checkContent(row)` (persists `content_claims`, updates `content.status`/`claim_check`); `guardOutput(text,{fallback,product})→{text,blocked,violations}`; `publicProduct(row)→product shape below`; `listDisplayableProducts()` (gate: `config.commerceEnabled` ⇒ only `regulatory_status='APPROVED'` AND `licence_reference`; else demo products shown with badge when `config.demoMode`).
- `engine/notifications.js`: `notify(userId,type,title,body,link)`, `ensureDailyPrompt(userId)` ("One question for you today.", max 1/day, respects `preferences.notifications`), `checkBaselineMilestone(userId)` ("You've completed your 7-day baseline."), `weeklyReady(userId)`.
- `engine/memory.js`: `buildContext(userId,purpose)` returns only the relevant slice: PROFILE, GOALS, PREFERENCES, WELLNESS_HISTORY, ROUTINES, CLINICIAN_CONTEXT, PRODUCT_CONTEXT, CONVERSATION_MEMORY.
- `engine/agents.js`: registry of 8 agents (onboarding_agent, question_selection_agent, wellness_summary_agent, routine_agent, conversation_agent, report_agent, safety_agent, claim_compliance_agent), each `{name, inputSchema, outputSchema, run(input)}` with `engine/schemas.js` validator (tiny JSON-schema subset); engine functions above route through them; LLM output is never written to important tables without passing the validator.
- `server/db/seed.js`: `seedReference()` (dimensions, questions: ≥10 assessment (one per dimension) + ≥40 daily with 5 labelled options each, routines (the 9 named in spec incl. Evening Wind-Down, Morning Reset, Workday Reset, Weekend Recovery, Screen-Free Evening, Movement Break, Breathing Break, Sleep Consistency, Digital Sunset), claim_rules (treats/cures/prevents/painkiller/guaranteed/diagnos/“clinically proven to” etc.), safety_rules, app_settings defaults, ≥14 content articles across all 12 categories incl. the 7 example titles, 4 DEMO products) and `seedDemo({reset})` (users above + history). Every content article and product copy must pass the claim checker. `scripts/migrate.js` runs `migrate()`; `scripts/seed.js [--reset]` runs both seeds.

## HTTP API (B implements; C/D consume)
JSON in/out. Errors: HTTP status + `{error:{code,message,fields?}}`. Session cookie `svara_sid` (HttpOnly). Every non-GET request from a logged-in user needs header `X-CSRF-Token` (value from `/api/auth/me` or login/signup response `csrf`). Roles: `USER`, `CLINICIAN`, `ADMIN` (admin may also use USER-only endpoints? NO — keep strict). Rate limits per IP (stricter on `/api/auth/*`, `/api/assessment/score`, `/api/guide/message`). Security headers + CSP (self only; inline styles allowed), body-size cap, input validation on every endpoint, audit log for sensitive actions (login, consent change, clinician share/view, export, delete, admin edits).

**Public**
- `GET /api/health` → `{status:'ok',version,time}`
- `GET /api/config` → `{demoMode,commerceEnabled,dimensions[],goals[],authProviders:{password,magic_link,google},features}`
- `GET /api/assessment/questions` → `{questions:[{id,dimension,question,response_type,options[5]}]}` (pool=assessment, active, in dimension order)
- `POST /api/assessment/score {answers:[{question_id,value}]}` → `{scores:{dim:n},answered}`
- `POST /api/snapshot/share {scores}` (only the 8 primary dims, ints 0–100; aggregate only) → `{slug,url}`; `GET /api/snapshot/:slug` → `{scores,created_at}`
- `POST /api/events {name,props?}` → 204 (whitelisted names: landing_view, wellness_check_started, wellness_check_completed, account_created, baseline_completed, check_in_completed, dashboard_viewed, weekly_report_viewed, routine_started, routine_completed, clinician_requested, clinician_report_shared, product_viewed, purchase_intent; props scrubbed to a small whitelist; no PII)
- `GET /api/content?category=` → `{categories:[…],articles:[{slug,title,category,summary,read_minutes}]}`; `GET /api/content/:slug` → `{article:{…,body(markdown-lite string)},disclaimer}` (published + claim-check passed only)
- `GET /api/routines` → `{routines:[{id,name,goal,duration_min,steps[],frequency,safety_notes,source_metadata,dimensions[]}]}`
- `GET /api/products` → `{demo:boolean,notice,products:[Product]}`; Product = `{id,name,category,manufacturer,ingredients[],formulation,description,regulatory_category,regulatory_status,licence_reference,approved_claims[],restricted_claims[],required_disclaimer,lab_report_url,batch_information,price,currency,stock,is_demo,badge:'DEMO — NOT FOR SALE'|null}`
- `POST /api/auth/signup {email,password,name?,assessment?:{answers},consents:{terms:true,privacy:true}}` → `{user:{id,email,role},csrf}` (sets cookie; records assessment check-ins kind `assessment`; consent rows; analytics `account_created`)
- `POST /api/auth/login {email,password}` / `POST /api/auth/logout` / `GET /api/auth/me` → `{user:null}` or `{user:{id,email,role,is_demo},profile,csrf}`
- `POST /api/demo/start {persona:'A'|'B'|'C'|'D'|'clinician'}` (DEMO_MODE only) → `{user,csrf}`; `GET /api/demo/personas` → `[{persona,name,blurb}]`

**USER** (role USER)
- `GET|PUT /api/profile` — `{name,age_range,timezone,lifestyle:{activity_level,work_pattern,sleep_schedule,lifestyle},preferences:{checkin_frequency,questions_per_day(1-3),focus_areas[],max_sensitivity,notifications:{daily,weekly,reports}},goals:[goal_key],consents:{ai_processing,analytics,marketing},onboarding_completed}`
- `GET /api/dashboard` → `{name,greeting_period,rhythm:[…getRhythm…],baseline:{…},reported:[string],patterns:[…],try_this:{routine_id,title,text},checked_in_today:boolean,unread_notifications:n}`
- `GET /api/trends?window=7|14|30|90|365` → getTrends shape
- `GET /api/checkin/next` → `{questions[],intro:'One question for you.',done_today:boolean,remaining:n,baseline:{…}}`
- `POST /api/checkin {answers:[{question_id,value,note?}],context?:{workload,exercised,late_screens}}` → `{saved:n,reflection:string,baseline:{…}}`
- `GET /api/guide/conversations`; `GET /api/guide/conversations/:id` → `{messages:[…]}`; `POST /api/guide/message {conversationId?,message}` → engine `respond` shape; `DELETE /api/guide/conversations/:id`
- `GET /api/rhythm/find?goal=key` → discovery.findRhythm; `GET /api/rhythm/goals` → `{goals:[…],active:[keys]}`; `POST /api/rhythm/goal {goal_key,active}`
- `GET /api/routines/activity` → `{activity:[…],completed_7d,streakless:true}`; `POST /api/routines/:id/start`; `POST /api/routines/:id/complete`
- `GET /api/weekly` (latest, generated on demand) → `{report:{id,week_start,content}}`; `GET /api/weekly/list`
- `GET /api/clinician/pathway` → `{reports:[…],clinicians:[{display_name,specialty,is_demo}],ranges:[7,30,90,null]}`; `POST /api/clinician/request {range_days,questions[],comments,consent:true}` → `{report}` (400 without explicit consent; builds snapshot via buildClinicianReport; auto-assigns least-loaded active clinician; notification; analytics); `GET /api/clinician/reports/:id` → `{report,content,notes(visible_to_user only)}`; `POST /api/clinician/reports/:id/revoke`
- `GET /api/notifications` → `{notifications[]}`; `POST /api/notifications/:id/read`; `POST /api/notifications/read-all`
- `GET /api/privacy` → `{collected:[{what,why,who,retention}],consents:{type:{granted,updated_at}},sharing:[reports],retention,statements:[…]}`; `PUT /api/privacy/consents {ai_processing?,marketing?,analytics?}`; `GET /api/privacy/export` (JSON attachment of everything); `POST /api/privacy/delete {password}` (hard delete, clears cookie); `GET /api/privacy/access-history` → `{entries:[{at,actor_role,action}]}` (actors shown as role, not identity)

**CLINICIAN** (role CLINICIAN; only reports assigned to them, not revoked; every view is audit-logged with `subject_user_id`)
- `GET /api/pro/overview` → `{counts:{requested,scheduled,in_consultation,completed},reports:[{id,user_name,status,range_days,created_at,scheduled_for}]}`; `GET /api/pro/users` → assigned users
- `GET /api/pro/reports/:id` → `{report,content,user:{name,age_range},notes[],demo:boolean}`
- `POST /api/pro/reports/:id/status {status,scheduled_for?}`; `POST /api/pro/reports/:id/notes {kind:'note'|'decision'|'next_step',body,visible_to_user?}`; `POST /api/pro/reports/:id/upload {file_name,mime,content_base64}` (≤2MB, pdf/png/jpg/txt; random server filename; stored under `data/uploads`)

**ADMIN** (role ADMIN)
- `GET /api/admin/overview` → counts; `GET /api/admin/resources/:resource` for `users|clinicians|products|questions|routines|content|claim_rules|safety_rules|dimensions`; `POST /api/admin/resources/:resource`; `PATCH /api/admin/resources/:resource/:id` (column whitelist per resource; `active` toggles; products/content writes run the claim checker and are rejected/flagged with violations; role changes audited)
- `GET|PUT /api/admin/settings` (AI config + flags); `GET /api/admin/analytics` → `{totals,funnel:[{name,count}],daily:[{day,events}]}`; `GET /api/admin/audit?limit=`; `GET /api/admin/safety-events`; `POST /api/admin/claims/check {text}`; `GET /api/admin/integrations` (placeholder registry from `server/integrations`); `POST /api/admin/clinicians {email,password,display_name,specialty,licence_reference}`

## Frontend contract
`public/index.html` loads `/styles.css`, `/app.css`, and `<script type="module" src="/js/main.js">`; mount points `#nav`, `#view`, `#toast`. Server serves `index.html` for any non-`/api`, non-file path.
**core.js exports (C)**: `h(tag,attrs,...children)` (hyperscript; `class`, `on*` handlers, `style` object, `html` NOT allowed—always text nodes/escaped), `$`, `api(method,path,body)` (JSON, credentials, CSRF header, throws `{status,message,fields}`), `state` `{user,profile,csrf,config}`, `refreshMe()`, `navigate(path)`, `toast(msg,type)`, `track(name,props)`, `fmt.date/relDay/pct`, `icon(name)`, `logo(size)`, `disclaimer(text?)`, `demoBadge()`, `loading()`, `errorBox(err)`, `emptyState(title,text,cta)`, `requireRole(role)`, and charts returning SVG elements: `rhythmRings(scores,{size})`, `radar(scores,{size})`, `sparkline(values,{w,h,color})`, `lineChart(series[{label,points[{x,y}]}],{w,h,baseline})`, `bar(value,{label})`, `dimIcon(key)`. `main.js` imports `routes` arrays from pages-public/pages-app/pages-pro and calls `startRouter(routes)`.
**Route shape**: `{path:'/learn/:slug', role:null|'USER'|'CLINICIAN'|'ADMIN', title, render:async(ctx)=>Node}`; `ctx={params,query,navigate}`. Router guards role (redirect `/login?next=`), updates `<title>`, scrolls top, re-renders shell nav by role.
**Paths**: public `/ /check /snapshot /signup /login /explore /learn /learn/:slug /products /s/:slug`; USER `/onboarding /home /checkin /guide /find /routines /weekly /trends /clinician /privacy /notifications`; CLINICIAN `/pro /pro/report/:id`; ADMIN `/admin /admin/:tab`.
**Assessment hand-off**: `/check` stores `sessionStorage['svara.assessment']=JSON.stringify({answers,scores})` → `/snapshot` shows it, "Save My Snapshot" → `/signup` which posts `assessment:{answers}`; after signup go to `/onboarding`, then `/home`. Share: `POST /api/snapshot/share` → link `/s/:slug`.
**CSS vocabulary (C defines in styles.css, D may use)**: tokens `--bg --surface --surface-2 --ink --ink-2 --muted --line --accent(sage green) --accent-2(earth) --warn --radius`; classes `.container .narrow .stack .row .grid .grid-2 .grid-3 .card .card-soft .btn .btn-primary .btn-ghost .btn-sm .pill .chip .chip.active .badge-demo .field .label .input .select .textarea .help .muted .eyebrow .h1 .h2 .h3 .lead .disclaimer .table .tabs .tab .tab.active .meter .stat .hr .sr-only .fade-in .callout .list`. D adds page-specific classes in `app.css` prefixed `a-`. Light + dark (prefers-color-scheme + `[data-theme]` toggle), mobile-first, subtle motion honoring `prefers-reduced-motion`.
**Palette/identity**: warm off-white `#F7F4EE`, soft charcoal `#2B2D2A`, muted sage `#7C9A8A`/deep `#4E6B5C`, earth clay `#B9906F`, sand `#E8E0D2`; one restrained accent. Premium sans (system stack: "Inter", ui-sans-serif, -apple-system, "Segoe UI"). Logo: abstract three-wave/arc mark in a soft circle. No leaf.
